// GENERATED by scripts/embed-migrations.mjs from ./drizzle -- do not edit by hand.
// Regenerate: npx drizzle-kit generate (in this package), then node scripts/embed-migrations.mjs (repo root).
import type { MigrationSet } from "@areelai/common";

export const userMigrations: MigrationSet = {
  table: "__migrations_user_management",
  migrations: [
  {
    tag: "0000_initial",
    sql: "CREATE TABLE `tokens` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text NOT NULL,\n\t`key_hash` text NOT NULL,\n\t`key_prefix` text NOT NULL,\n\t`key_ciphertext` text,\n\t`key_iv` text,\n\t`key_tag` text,\n\t`owner_user_id` integer,\n\t`scope_services_json` text,\n\t`max_requests` integer,\n\t`max_tokens` integer,\n\t`used_requests` integer DEFAULT 0 NOT NULL,\n\t`used_tokens` integer DEFAULT 0 NOT NULL,\n\t`expires_at` integer,\n\t`enabled` integer DEFAULT true NOT NULL,\n\t`created_at` integer DEFAULT (strftime('%s','now') * 1000) NOT NULL,\n\tFOREIGN KEY (`owner_user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `tokens_hash_idx` ON `tokens` (`key_hash`);--> statement-breakpoint\nCREATE TABLE `users` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`username` text NOT NULL,\n\t`password_hash` text NOT NULL,\n\t`role` text DEFAULT 'manager' NOT NULL,\n\t`enabled` integer DEFAULT true NOT NULL,\n\t`must_change_password` integer DEFAULT false NOT NULL,\n\t`created_at` integer DEFAULT (strftime('%s','now') * 1000) NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `users_username_idx` ON `users` (`username`);",
  },
  ],
};
