// GENERATED by scripts/embed-migrations.mjs from ./drizzle -- do not edit by hand.
// Regenerate: npx drizzle-kit generate (in this package), then node scripts/embed-migrations.mjs (repo root).
import type { MigrationSet } from "@areelai/common";

export const modelServiceMigrations: MigrationSet = {
  table: "__migrations_model_services",
  migrations: [
  {
    tag: "0000_initial",
    sql: "CREATE TABLE `hosted_tools` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text NOT NULL,\n\t`config_json` text NOT NULL,\n\t`headers_secret` text NOT NULL,\n\t`enabled` integer DEFAULT true NOT NULL,\n\t`created_at` integer DEFAULT (strftime('%s','now') * 1000) NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `hosted_tools_name_idx` ON `hosted_tools` (`name`);--> statement-breakpoint\nCREATE TABLE `model_services` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text NOT NULL,\n\t`description` text,\n\t`kind` text DEFAULT 'model_service' NOT NULL,\n\t`definition_json` text NOT NULL,\n\t`enabled` integer DEFAULT true NOT NULL,\n\t`created_at` integer DEFAULT (strftime('%s','now') * 1000) NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `service_name_idx` ON `model_services` (`name`);--> statement-breakpoint\nCREATE TABLE `service_tools` (\n\t`service_id` integer NOT NULL,\n\t`tool_id` integer NOT NULL,\n\tFOREIGN KEY (`service_id`) REFERENCES `model_services`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`tool_id`) REFERENCES `hosted_tools`(`id`) ON UPDATE no action ON DELETE cascade\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `service_tools_pair_idx` ON `service_tools` (`service_id`,`tool_id`);",
  },
  ],
};
