// GENERATED by scripts/embed-migrations.mjs from ./drizzle -- do not edit by hand.
// Regenerate: npx drizzle-kit generate (in this package), then node scripts/embed-migrations.mjs (repo root).
import type { MigrationSet } from "@areelai/common";

export const microAgentMigrations: MigrationSet = {
  table: "__migrations_micro_agent",
  migrations: [
  {
    tag: "0000_initial",
    sql: "CREATE TABLE `image_cache` (\n\t`hash` text PRIMARY KEY NOT NULL,\n\t`description` text NOT NULL,\n\t`size_bytes` integer NOT NULL,\n\t`last_used_at` integer NOT NULL,\n\t`created_at` integer DEFAULT (strftime('%s','now') * 1000) NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `image_cache_last_used_idx` ON `image_cache` (`last_used_at`);",
  },
  ],
};
